name: Java CI (Manual JUnit)

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up JDK
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Download JUnit and Hamcrest
      run: |
        mkdir lib
        curl -L -o lib/junit-4.13.2.jar https://search.maven.org/remotecontent?filepath=junit/junit/4.13.2/junit-4.13.2.jar
        curl -L -o lib/hamcrest-core-1.3.jar https://search.maven.org/remotecontent?filepath=org/hamcrest/hamcrest-core/1.3/hamcrest-core-1.3.jar

    - name: Compile Java code
      run: |
        mkdir -p out
        javac -cp "lib/*" -d out bath-students/src/wars/*.java baths-students/test/warTesting/*.java

    - name: Run JUnit tests
      run: |
        cd out
        java -cp ".:../lib/*" org.junit.runner.JUnitCore warTesting.T1InitializationTest
